# Generated by Django 4.2.5 on 2023-09-22 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproductaccess',
            name='lesson',
        ),
    ]
